version: '3'

services:
  #PHP Service
  laravel_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      DB_HOST: laravel_db
      DB_PORT: 5432
      DB_DATABASE: database
      DB_USERNAME: postgres
      DB_PASSWORD: 123456

    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  laravel_webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

  laravel_db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: database
    volumes:
      - ./volumes/dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local